<a href="https://colab.research.google.com/github/TradMod/Students_Data_Management/blob/main/students_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [75]:
import pandas as pd
import numpy as np

In [76]:
df = pd.read_csv("student_performance.csv")
df

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A
999996,999997,15.7,82.7,6.7,88.3,A
999997,999998,14.2,85.1,5.8,87.9,A
999998,999999,25.3,90.0,5.3,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

### How many rows and columns are there in the dataset?

In [77]:
df.shape[0] #rows 1, cols 0
df.shape[1]

6

### Show the first 10 rows of the dataset.

In [78]:
df.head(10)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
5,6,13.4,65.1,5.0,97.5,A
6,7,26.1,81.8,5.9,100.0,A
7,8,20.4,100.0,4.0,96.1,A
8,9,11.7,100.0,8.2,69.8,C
9,10,18.8,67.6,6.0,80.3,B

### Show the last 10 rows of the dataset.

In [79]:
df.tail(10)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
999990,999991,15.4,82.8,4.0,86.9,A
999991,999992,30.0,87.4,6.7,100.0,A
999992,999993,26.3,84.6,4.5,100.0,A
999993,999994,20.7,82.4,5.5,99.1,A
999994,999995,15.1,77.0,9.2,80.5,B
999995,999996,18.0,95.5,4.8,100.0,A
999996,999997,15.7,82.7,6.7,88.3,A
999997,999998,14.2,85.1,5.8,87.9,A
999998,999999,25.3,90.0,5.3,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

### What are the column names in the dataset?

In [80]:
df.columns

Index(['student_id', 'weekly_self_study_hours', 'attendance_percentage',
       'class_participation', 'total_score', 'grade'],
      dtype='object')

### What is the maximum value of weekly_self_study_hours?

In [81]:
df["weekly_self_study_hours"].max()

40.0

### Which student studied the most hours in a week?

In [82]:
df.loc[df["weekly_self_study_hours"].max()]

student_id                    41
weekly_self_study_hours     20.2
attendance_percentage       85.6
class_participation          5.6
total_score                100.0
grade                          A
Name: 40, dtype: object

### Show the top 5 students by weekly_self_study_hours.

In [83]:
sorted = df.sort_values(by="weekly_self_study_hours")
sorted.tail(5)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
937007,937008,40.0,67.6,6.3,100.0,A
156138,156139,40.0,81.3,6.2,100.0,A
895979,895980,40.0,86.7,6.7,100.0,A
539838,539839,40.0,63.1,2.9,100.0,A
721029,721030,40.0,74.0,5.3,100.0,A

### Which student has the highest attendance percentage?

In [84]:
df[df["attendance_percentage"] == df["attendance_percentage"].max()]

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
7,8,20.4,100.0,4.0,96.1,A
8,9,11.7,100.0,8.2,69.8,C
18,19,8.6,100.0,9.0,75.4,B
22,23,15.5,100.0,8.5,76.3,B
44,45,4.7,100.0,3.3,55.9,C
...,...,...,...,...,...,...
999919,999920,10.9,100.0,7.9,67.6,C
999921,999922,7.0,100.0,6.9,66.2,C
999931,999932,10.4,100.0,5.8,69.3,C
999938,999939,13.7,100.0,4.3,98.8,A
999939,999940,8.9,100.0,7.8,73.4,B

### Which student has the highest class participation?

In [85]:
df.loc[df["class_participation"].idxmax()]

student_id                  138
weekly_self_study_hours    12.7
attendance_percentage      78.3
class_participation        10.0
total_score                78.7
grade                         B
Name: 137, dtype: object

### Create a new column score_level
"High" if total_score ≥ 90 , "Medium" if 70 ≤ total_score < 90, "Low" if total_score < 70

In [86]:
def func(total_score):
  if total_score >= 90:
    return "High"
  elif total_score < 90 and total_score >= 70:
    return "Medium"
  else:
    return "Low"

In [87]:
df["score_level"] = df["total_score"].apply(func)
df

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,score_level
0,1,18.5,95.6,3.8,97.9,A,High
1,2,14.0,80.0,2.5,83.9,B,Medium
2,3,19.5,86.3,5.3,100.0,A,High
3,4,25.7,70.2,7.0,100.0,A,High
4,5,13.4,81.9,6.9,92.0,A,High
...,...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A,High
999996,999997,15.7,82.7,6.7,88.3,A,Medium
999997,999998,14.2,85.1,5.8,87.9,A,Medium
999998,999999,25.3,90.0,5.3,100.0,A,High
999999,1000000,18.3,84.6,4.1,100.0,A,High

### Which student has the highest total_score?

In [88]:
df.loc[df["total_score"].idxmax()]

student_id                     3
weekly_self_study_hours     19.5
attendance_percentage       86.3
class_participation          5.3
total_score                100.0
grade                          A
score_level                 High
Name: 2, dtype: object

### How many students scored exactly 100 in total_score?

In [89]:
(df["total_score"] == 100).sum()

np.int64(268121)

### Make a new column for study efficiency = total_score ÷ weekly_self_study_hours.

In [90]:
df["study_efficiency"] = df["total_score"] / df["weekly_self_study_hours"]
df

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,score_level,study_efficiency
0,1,18.5,95.6,3.8,97.9,A,High,5.291892
1,2,14.0,80.0,2.5,83.9,B,Medium,5.992857
2,3,19.5,86.3,5.3,100.0,A,High,5.128205
3,4,25.7,70.2,7.0,100.0,A,High,3.891051
4,5,13.4,81.9,6.9,92.0,A,High,6.865672
...,...,...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A,High,5.555556
999996,999997,15.7,82.7,6.7,88.3,A,Medium,5.624204
999997,999998,14.2,85.1,5.8,87.9,A,Medium,6.190141
999998,999999,25.3,90.0,5.3,100.0,A,High,3.952569
999999,1000000,18.3,84.6,4.1,100.0,A,High,5.464481

### Create a new column study_category
"Light" if weekly_self_study_hours < 10,
"Moderate" if 10 ≤ hours ≤ 20,
"Heavy" if hours > 20

In [91]:
def categorize_study(hours):
    if hours < 10:
        return "Light"
    elif hours <= 20: # Since it's not < 10, we know it's >= 10
        return "Moderate"
    else:
        return "Heavy"

df["study_category"] = df["weekly_self_study_hours"].apply(categorize_study)
df

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,score_level,study_efficiency,study_category
0,1,18.5,95.6,3.8,97.9,A,High,5.291892,Moderate
1,2,14.0,80.0,2.5,83.9,B,Medium,5.992857,Moderate
2,3,19.5,86.3,5.3,100.0,A,High,5.128205,Moderate
3,4,25.7,70.2,7.0,100.0,A,High,3.891051,Heavy
4,5,13.4,81.9,6.9,92.0,A,High,6.865672,Moderate
...,...,...,...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A,High,5.555556,Moderate
999996,999997,15.7,82.7,6.7,88.3,A,Medium,5.624204,Moderate
999997,999998,14.2,85.1,5.8,87.9,A,Medium,6.190141,Moderate
999998,999999,25.3,90.0,5.3,100.0,A,High,3.952569,Heavy
999999,1000000,18.3,84.6,4.1,100.0,A,High,5.464481,Moderate

In [92]:
# Define the conditions based on your hours thresholds
conditions = [
    df["weekly_self_study_hours"] < 10,
    (df["weekly_self_study_hours"] >= 10) & (df["weekly_self_study_hours"] <= 20)
]

# Define the matching category labels
choices = ["Light", "Moderate"]

# np.select applies choices based on conditions; the default handles hours > 20 ("Heavy")
df["study_category"] = np.select(conditions, choices, default="Heavy")
df

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,score_level,study_efficiency,study_category
0,1,18.5,95.6,3.8,97.9,A,High,5.291892,Moderate
1,2,14.0,80.0,2.5,83.9,B,Medium,5.992857,Moderate
2,3,19.5,86.3,5.3,100.0,A,High,5.128205,Moderate
3,4,25.7,70.2,7.0,100.0,A,High,3.891051,Heavy
4,5,13.4,81.9,6.9,92.0,A,High,6.865672,Moderate
...,...,...,...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A,High,5.555556,Moderate
999996,999997,15.7,82.7,6.7,88.3,A,Medium,5.624204,Moderate
999997,999998,14.2,85.1,5.8,87.9,A,Medium,6.190141,Moderate
999998,999999,25.3,90.0,5.3,100.0,A,High,3.952569,Heavy
999999,1000000,18.3,84.6,4.1,100.0,A,High,5.464481,Moderate